##### ENV VARS that must be set prior to build
# PKG_VER - 0.0.1 etc
# PKG_TYPE - a, b, rc1, rc2, etc


### PKG_TYPE tells us the stage of the release cycle we are in
# a for alpha
# b for beta
# rc1 for release candidate 1
# see https://en.wikipedia.org/wiki/Software_release_life_cycle


package:
  name: sample_project
  version: {PKG_VER}


##### source outlines where the package data is obtained. Uncomment only ONE of these.
# The data source files will be copied from the provided location into the build directory
# then, the build script (build.bat or build.sh depending on the OS) will be executed in that
# directory to build the software.

### local filesystem http://conda.pydata.org/docs/build_tutorials.html
#source:
##### local filesystem
#  fn:  boost_1_60_0.tar.bz2
#  url: http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.bz2
#  md5: 65a840e1a0b13a558ff19eeb2c4f0cbe
# todo document patches
#  patches:
#      - my.patch # the patch file is expected to be found in the recipe

### webserver
#  fn:  boost_1_60_0.tar.bz2
#  url: http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.bz2
#  md5: 65a840e1a0b13a558ff19eeb2c4f0cbe
# todo document patches
#  patches:
#      - my.patch # the patch file is expected to be found in the recipe

### remote version control (svn)
#  svn_url: https://github.com/ilanschnell/bsdiff
#  svn_rev: 1.1.4
#  svn_ignore_externals: True # (defaults to False)
# todo document patches
#  patches:
#      - my.patch # the patch file is expected to be found in the recipe

### remote version control (hg) mercurial
#  hg_url: ssh://hg@bitbucket.org/ilanschnell/bsdiff4
#  hg_tag: release/1.1.4
# todo document patches
#  patches:
#      - my.patch # the patch file is expected to be found in the recipe

### remote version control (git)
#  git_url: https://github.com/ilanschnell/bsdiff4.git
#  git_rev: release/1.1.4
# here, release/1.1.4 is the name of a branch or tag
# todo document patches
#  patches:
#      - my.patch # the patch file is expected to be found in the recipe

### local version control (git)
#  git_url: https://github.com/ilanschnell/bsdiff4.git
#  git_rev: release/1.1.4
# here, release/1.1.4 is the name of a branch or tag
# todo document patches
#  patches:
#      - my.patch # the patch file is expected to be found in the recipe



##### build is... <TODO NEEDS MORE DOCUMENTATION!!!>
build:
  # TODO Advanced Usage. might change
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]


##### Requirements. We specify what packages we depend on in various operating systems here.
requirements:

  ### Packages that must be installed for us to build this package
  build:
    - python
    - setuptools
    # replace with modules your package needs during build.
#    - icu               [unix]
#    - bzip2             [unix]
#    - zlib

  ### Packages that must be installed for us to run this module
  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python
    - icu               [unix]
    - zlib

test:
  # Test that these modules are importable
  imports:
    - sympy
    - sympy.assumptions
    - sympy.assumptions.handlers
    - sympy.assumptions.tests
    - sympy.calculus
    - sympy.calculus.tests

  # todo test suite could take a long time to run use jinja2 to turn tests on and off?
  #
  # TODO test using pytest cov?
  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # TODO demo run_test.py
  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # todo lists packages required only for testing
  # requires:
    # Put any additional test requirements here.  For example
    # - nose
    # - pytest >= 2.7

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: 'Computer algebra system (CAS) in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

